datasets:
  - name: rxrx1
    tar_path: Data/rxrx1_v1.0.tar
    root_dir: "${SLURM_TMPDIR}/data/rxrx1_v1.0"
    num_classes: 1139
  - name: iwildcam
    tar_path: Data/iwildcam_v2.0.tar
    root_dir: "${SLURM_TMPDIR}/data/iwildcam_v2.0"
    num_classes: 182
  - name: caltech256
    # tar_path: Data/iwildcam_v2.0.tar
    root_dir: "${SLURM_TMPDIR}/data/caltech256"
    num_classes: 257